### ISSUE TITLE
Gradle install

### ISSUE THREAD

**Issue by guillaumeagile** [sfauvel/documentationtesting#7]
I will figure out to do it by myself, but if someone know the Gradle equivalent of the POM dependency to install this lib, I'd be delighted.

**Comment by guillaumeagile** [comment]
found this. https://sagioto.github.io/maven2gradle/

**Comment by guillaumeagile** [comment]
Doesn't work
> Could not find method compile() for arguments [org.sfvl:documentationtesting:1.1.20] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

I come from C#
I'm not very good with Gradle, obviously :(

**Comment by guillaumeagile** [comment]
Ok, I've tried to put the dependency declaration in TestImplementation, and it says:
Could not find org.sfvl:documentationtesting:1.1.20.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/org/sfvl/documentationtesting/1.1.20/documentationtesting-1.1.20.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact


Any clue which repository to search (and how to tell gradle to look into it?)

**Comment by sfauvel** [comment]
The library is not yet deployed in a public repository. 
You can find explanation here to install it: https://sfauvel.github.io/documentationtesting/documentationtesting/org/sfvl/howto/Tutorial.html
or you can use this project that embedded the library:
https://github.com/sfauvel/TryDocAsTest
I'm not very good with Gradle either. Don't hesitate to make a proposal if you know how to do it

**Comment by guillaumeagile** [comment]
OK, thanks. will try.
Meanwhile, I try to generate gradle file from the pom of your TryDocAsTest project
Copy/paste relevant things from the generated gradle into mine.
Then add the POM from your project to mine.
Then it build ok.

Let's see if it works when running tests...

**Comment by guillaumeagile** [comment]
OK, thanks. will try.
Meanwhile, I try to generate a gradle file from the pom of your TryDocAsTest project
Copy/paste relevant things from the generated gradle into mine.
Then add the POM from your project to mine.
But still the JAR has to be "installed" and I don't know how in case of Gradle project. Still trying to find out.

Mmmmmh, I love the JVM, everything is so easy to setup 🤣

**Comment by sfauvel** [comment]
You can found an example of gradle configuration here: https://github.com/sfauvel/TryDocAsTest/tree/gradle
